[package]
name = "good_first_issue"
version = "0.2.0"
edition = "2024"

[dependencies]
flate2 = "1.0"
serde_json = "1.0"
rusqlite = { version = "0.31", features = ["bundled"] }
time = "0.3"
ureq = "2"