[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "gzip"] }
flate2 = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
rusqlite = "0.32"
chrono = "0.4"
